### Домашнее задание "Продвинутая линейная алгебра".
## Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)  
## Уровень 1:
Найдите спектральное разложение матрицы:

m = np.array([[1, 2],
              [2,3]])
print(m)
Постройте зависимость качества восстановления рукописных цифр (MNIST) в зависимости от различного количества компонент PCA. В качестве метрики различия предлагаю использовать MSE.*

## Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

* a) Диагональная, ортогональная, но не единичная(!)

In [17]:
import numpy as np

In [18]:
diag_m = np.diag([-1, -1, -1, -1])
diag_m

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [20]:
# проверяю на ортогональность
diag_mT = diag_m.transpose()
diag_m.dot(diag_mT)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

* Верхнетреугольная, ортогональная

In [23]:
diag_m
X = np.triu(diag_m,0)
X

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [24]:
# проверяю на ортогональность
XT = X.transpose()
X.dot(XT)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

* Нижнетреугольная, ортогональная

In [25]:
diag_m
X1 = np.triu(diag_m,0)
X1

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

* Матрица, у которой определитель = 1, и все элементы не равны 0

In [31]:
A = np.array([[5,1, 4], [1,1, 1 ], [6,1, 5 ]])
A

array([[5, 1, 4],
       [1, 1, 1],
       [6, 1, 5]])

In [32]:
np.linalg.det(A)

0.9999999999999971

* Найдите собственные значения и собственные вектора матриц:

In [54]:
m = np.array([[2, 2], [1, 3]]) 
print(m)

[[2 2]
 [1 3]]


In [55]:
w, v = np.linalg.eig(m)

In [60]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))    
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


## Уровень 1

* Найдите спектральное разложение матрицы:

In [11]:
import numpy as np
from numpy import linalg

In [12]:
m = np.array([[1, 2], [2,3]]) 
print(m) 

[[1 2]
 [2 3]]


In [15]:
w, v = linalg.eig(m)
print('Собственное значение:')
print(np.array(w, dtype = float))
print('соответствующий ему собственный вектор:')
print(v)

Собственное значение:
[-0.23606798  4.23606798]
соответствующий ему собственный вектор:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [16]:
print(np.array(v.dot(np.diag(w)).dot(v.T), dtype = float))

[[1. 2.]
 [2. 3.]]
